algoritmo "crie um algoritmo que peça dois números e no final mostre o maior deles."
var
num1,num2: inteiro
inicio
escreval("Algoritimo GPT-3500")

escreval("Escreva um numero inteiro")
escreva("R:")
leia(num1)
escreval("Tranquilo agora escreva outro")
escreva("R:")
leia(num2)

escreval
escreval("Entre os valores informados",num1," e",num2)
escreval

se(num1 > num2) entao
        escreval("O maior é o", num1)
senao
        escreval("O maior é o", num2)
fimse

fimalgoritmo